name: projeto_login_cadastro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_modular: ^3.3.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  connectivity_plus: ^6.0.3
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - lib/assets/comida.jpg
  - lib/assets/logo_potato.png
